### ISSUE TITLE
Customizable user helpers

### ISSUE THREAD

**Issue by agis-** [skroutz/cogy#36]
We should provide a way for users to define their own helpers, like `user` or something, that will be available inside commands and will return the Rails `User` object. It should be configurable like this:

```ruby
Cogy.configure do |c|
  c.user_lambda = ->(id) { User.find(id) }
end
```

Then the helper could just call this lambda with the Cogy ENV as the argument.

Blocked on #35.

**Comment by ctrochalakis** [comment]
Alternate syntax:

```ruby
c.attribute(:user) { |env| User.find_by_id(env['COGY_UID']) }
```

**Comment by agis-** [comment]
We should also probably provide some default ones (like `args` and `opts`).
